from sqlalchemy import select
from app.db.database import SessionLocal
from app.models.fighter import Fighter


SEED_FIGHTERS = [
    {
        "name": "Islam Makhachev",
        "height": "5'10\"",
        "weight": 155,
        "reach": 70.5,
        "stance": "Orthodox",
        "strikes_per_min": 2.4,
        "takedowns_avg": 4.2,
        "submission_avg": 0.9,
        "defense": 82,
        "striking": 72,
        "wrestling": 95,
        "cardio": 80,
        "wins": 25,
        "losses": 1,
        "win_streak": 14,
        "strike_accuracy": 59,
        "td_defense": 90,
    },
    {
        "name": "Charles Oliveira",
        "height": "5'10\"",
        "weight": 155,
        "reach": 74.0,
        "stance": "Orthodox",
        "strikes_per_min": 3.6,
        "takedowns_avg": 1.1,
        "submission_avg": 2.8,
        "defense": 65,
        "striking": 78,
        "wrestling": 60,
        "cardio": 85,
        "wins": 34,
        "losses": 9,
        "win_streak": 6,
        "strike_accuracy": 56,
        "td_defense": 58,
    },
    {
        "name": "Justin Gaethje",
        "height": "5'11\"",
        "weight": 155,
        "reach": 70.0,
        "stance": "Orthodox",
        "strikes_per_min": 7.6,
        "takedowns_avg": 0.5,
        "submission_avg": 0.0,
        "defense": 58,
        "striking": 90,
        "wrestling": 55,
        "cardio": 70,
        "wins": 25,
        "losses": 4,
        "win_streak": 3,
        "strike_accuracy": 55,
        "td_defense": 75,
    },
    {
        "name": "Max Holloway",
        "height": "5'11\"",
        "weight": 155,
        "reach": 69.0,
        "stance": "Orthodox",
        "strikes_per_min": 6.4,
        "takedowns_avg": 0.4,
        "submission_avg": 0.1,
        "defense": 60,
        "striking": 88,
        "wrestling": 40,
        "cardio": 95,
        "wins": 25,
        "losses": 7,
        "win_streak": 2,
        "strike_accuracy": 48,
        "td_defense": 68,
    },
    {
        "name": "Petr Yan",
        "height": "5'7\"",
        "weight": 135,
        "reach": 67.0,
        "stance": "Orthodox",
        "strikes_per_min": 5.9,
        "takedowns_avg": 1.2,
        "submission_avg": 0.2,
        "defense": 75,
        "striking": 85,
        "wrestling": 65,
        "cardio": 82,
        "wins": 17,
        "losses": 4,
        "win_streak": 1,
        "strike_accuracy": 51,
        "td_defense": 83,
    },
    {
        "name": "Deiveson Figueiredo",
        "height": "5'5\"",
        "weight": 135,
        "reach": 68.0,
        "stance": "Orthodox",
        "strikes_per_min": 4.1,
        "takedowns_avg": 1.5,
        "submission_avg": 0.8,
        "defense": 70,
        "striking": 78,
        "wrestling": 70,
        "cardio": 72,
        "wins": 23,
        "losses": 3,
        "win_streak": 2,
        "strike_accuracy": 46,
        "td_defense": 73,
    },
    {
        "name": "Alex Pereira",
        "height": "6'4\"",
        "weight": 205,
        "reach": 79.0,
        "stance": "Southpaw",
        "strikes_per_min": 5.1,
        "takedowns_avg": 0.0,
        "submission_avg": 0.0,
        "defense": 55,
        "striking": 95,
        "wrestling": 30,
        "cardio": 65,
        "wins": 11,
        "losses": 2,
        "win_streak": 5,
        "strike_accuracy": 56,
        "td_defense": 50,
    },
    {
        "name": "Jamahal Hill",
        "height": "6'4\"",
        "weight": 205,
        "reach": 79.5,
        "stance": "Orthodox",
        "strikes_per_min": 5.5,
        "takedowns_avg": 0.3,
        "submission_avg": 0.0,
        "defense": 50,
        "striking": 82,
        "wrestling": 35,
        "cardio": 70,
        "wins": 12,
        "losses": 2,
        "win_streak": 1,
        "strike_accuracy": 50,
        "td_defense": 55,
    },
]


async def seed_fighters():
    async with SessionLocal() as session:
        result = await session.execute(select(Fighter).limit(1))
        if result.scalars().first():
            return
        for data in SEED_FIGHTERS:
            session.add(Fighter(**data))
        await session.commit()
