from sqlalchemy import select
from app.db.database import SessionLocal
from app.models.fighter import Fighter


SEED_FIGHTERS = [
    # UFC 327 Main Event
    {
        "name": "Jiri Prochazka",
        "height": "6'4\"",
        "weight": 205,
        "reach": 80.0,
        "stance": "Orthodox",
        "strikes_per_min": 6.2,
        "takedowns_avg": 0.5,
        "submission_avg": 0.4,
        "defense": 52,
        "striking": 88,
        "wrestling": 40,
        "cardio": 78,
        "wins": 32,
        "losses": 5,
        "win_streak": 2,
        "strike_accuracy": 55,
        "td_defense": 56,
    },
    {
        "name": "Carlos Ulberg",
        "height": "6'4\"",
        "weight": 205,
        "reach": 78.0,
        "stance": "Southpaw",
        "strikes_per_min": 4.8,
        "takedowns_avg": 0.3,
        "submission_avg": 0.0,
        "defense": 60,
        "striking": 84,
        "wrestling": 35,
        "cardio": 75,
        "wins": 14,
        "losses": 1,
        "win_streak": 9,
        "strike_accuracy": 57,
        "td_defense": 68,
    },
    # Co-Main
    {
        "name": "Azamat Murzakanov",
        "height": "5'11\"",
        "weight": 205,
        "reach": 74.5,
        "stance": "Orthodox",
        "strikes_per_min": 4.5,
        "takedowns_avg": 1.8,
        "submission_avg": 0.0,
        "defense": 62,
        "striking": 76,
        "wrestling": 72,
        "cardio": 70,
        "wins": 14,
        "losses": 1,
        "win_streak": 5,
        "strike_accuracy": 53,
        "td_defense": 80,
    },
    {
        "name": "Paulo Costa",
        "height": "6'0\"",
        "weight": 205,
        "reach": 72.0,
        "stance": "Orthodox",
        "strikes_per_min": 7.1,
        "takedowns_avg": 0.5,
        "submission_avg": 0.0,
        "defense": 55,
        "striking": 85,
        "wrestling": 38,
        "cardio": 58,
        "wins": 14,
        "losses": 4,
        "win_streak": 1,
        "strike_accuracy": 57,
        "td_defense": 60,
    },
    # Heavyweight
    {
        "name": "Curtis Blaydes",
        "height": "6'2\"",
        "weight": 265,
        "reach": 80.0,
        "stance": "Orthodox",
        "strikes_per_min": 3.4,
        "takedowns_avg": 5.3,
        "submission_avg": 0.4,
        "defense": 58,
        "striking": 65,
        "wrestling": 92,
        "cardio": 72,
        "wins": 18,
        "losses": 5,
        "win_streak": 1,
        "strike_accuracy": 51,
        "td_defense": 70,
    },
    {
        "name": "Josh Hokit",
        "height": "6'1\"",
        "weight": 265,
        "reach": 76.0,
        "stance": "Orthodox",
        "strikes_per_min": 3.8,
        "takedowns_avg": 2.5,
        "submission_avg": 0.0,
        "defense": 52,
        "striking": 68,
        "wrestling": 75,
        "cardio": 65,
        "wins": 9,
        "losses": 1,
        "win_streak": 4,
        "strike_accuracy": 49,
        "td_defense": 65,
    },
    # Light Heavyweight
    {
        "name": "Dominick Reyes",
        "height": "6'4\"",
        "weight": 205,
        "reach": 77.0,
        "stance": "Orthodox",
        "strikes_per_min": 4.6,
        "takedowns_avg": 0.6,
        "submission_avg": 0.0,
        "defense": 50,
        "striking": 80,
        "wrestling": 42,
        "cardio": 68,
        "wins": 12,
        "losses": 4,
        "win_streak": 1,
        "strike_accuracy": 47,
        "td_defense": 72,
    },
    {
        "name": "Johnny Walker",
        "height": "6'5\"",
        "weight": 205,
        "reach": 82.5,
        "stance": "Orthodox",
        "strikes_per_min": 4.2,
        "takedowns_avg": 0.3,
        "submission_avg": 0.5,
        "defense": 48,
        "striking": 78,
        "wrestling": 35,
        "cardio": 62,
        "wins": 21,
        "losses": 9,
        "win_streak": 2,
        "strike_accuracy": 46,
        "td_defense": 52,
    },
    # Featherweight
    {
        "name": "Cub Swanson",
        "height": "5'8\"",
        "weight": 145,
        "reach": 70.0,
        "stance": "Orthodox",
        "strikes_per_min": 5.3,
        "takedowns_avg": 0.8,
        "submission_avg": 0.5,
        "defense": 58,
        "striking": 78,
        "wrestling": 50,
        "cardio": 72,
        "wins": 29,
        "losses": 13,
        "win_streak": 1,
        "strike_accuracy": 44,
        "td_defense": 70,
    },
    {
        "name": "Nate Landwehr",
        "height": "5'9\"",
        "weight": 145,
        "reach": 70.0,
        "stance": "Southpaw",
        "strikes_per_min": 7.2,
        "takedowns_avg": 1.6,
        "submission_avg": 0.3,
        "defense": 52,
        "striking": 82,
        "wrestling": 58,
        "cardio": 80,
        "wins": 17,
        "losses": 6,
        "win_streak": 2,
        "strike_accuracy": 51,
        "td_defense": 62,
    },
    # Featherweight Prelim
    {
        "name": "Patricio Pitbull",
        "height": "5'7\"",
        "weight": 145,
        "reach": 68.0,
        "stance": "Orthodox",
        "strikes_per_min": 4.8,
        "takedowns_avg": 0.7,
        "submission_avg": 0.4,
        "defense": 62,
        "striking": 82,
        "wrestling": 55,
        "cardio": 78,
        "wins": 36,
        "losses": 8,
        "win_streak": 1,
        "strike_accuracy": 48,
        "td_defense": 74,
    },
    {
        "name": "Aaron Pico",
        "height": "5'8\"",
        "weight": 145,
        "reach": 69.0,
        "stance": "Orthodox",
        "strikes_per_min": 5.5,
        "takedowns_avg": 2.8,
        "submission_avg": 0.2,
        "defense": 55,
        "striking": 80,
        "wrestling": 78,
        "cardio": 72,
        "wins": 13,
        "losses": 3,
        "win_streak": 5,
        "strike_accuracy": 50,
        "td_defense": 70,
    },
    # Welterweight
    {
        "name": "Kevin Holland",
        "height": "6'3\"",
        "weight": 170,
        "reach": 81.0,
        "stance": "Orthodox",
        "strikes_per_min": 5.1,
        "takedowns_avg": 0.5,
        "submission_avg": 0.8,
        "defense": 50,
        "striking": 78,
        "wrestling": 38,
        "cardio": 68,
        "wins": 26,
        "losses": 12,
        "win_streak": 1,
        "strike_accuracy": 46,
        "td_defense": 42,
    },
    {
        "name": "Randy Brown",
        "height": "6'3\"",
        "weight": 170,
        "reach": 78.0,
        "stance": "Southpaw",
        "strikes_per_min": 4.0,
        "takedowns_avg": 1.2,
        "submission_avg": 0.5,
        "defense": 58,
        "striking": 72,
        "wrestling": 55,
        "cardio": 72,
        "wins": 18,
        "losses": 6,
        "win_streak": 3,
        "strike_accuracy": 49,
        "td_defense": 68,
    },
    # Lightweight
    {
        "name": "Mateusz Gamrot",
        "height": "5'10\"",
        "weight": 155,
        "reach": 70.0,
        "stance": "Southpaw",
        "strikes_per_min": 4.7,
        "takedowns_avg": 3.5,
        "submission_avg": 0.7,
        "defense": 62,
        "striking": 75,
        "wrestling": 85,
        "cardio": 82,
        "wins": 24,
        "losses": 3,
        "win_streak": 3,
        "strike_accuracy": 48,
        "td_defense": 78,
    },
    {
        "name": "Esteban Ribovics",
        "height": "5'10\"",
        "weight": 155,
        "reach": 72.0,
        "stance": "Southpaw",
        "strikes_per_min": 5.8,
        "takedowns_avg": 0.4,
        "submission_avg": 0.3,
        "defense": 50,
        "striking": 80,
        "wrestling": 40,
        "cardio": 70,
        "wins": 14,
        "losses": 3,
        "win_streak": 2,
        "strike_accuracy": 52,
        "td_defense": 55,
    },
]


async def seed_fighters():
    async with SessionLocal() as session:
        result = await session.execute(select(Fighter).limit(1))
        if result.scalars().first():
            return
        for data in SEED_FIGHTERS:
            session.add(Fighter(**data))
        await session.commit()
